/usr/local/fsl/bin/run_first -i MNI152_T1_1mm_brain -t MNI152_T1_1mm_brain_to_std_sub.mat -n 50 -o MNI/MNI_FIRST-L_Accu_first -m /usr/local/fsl/data/first/models_336_bin/L_Accu_bin.bmv; /usr/local/fsl/bin/first_boundary_corr -s MNI/MNI_FIRST-L_Accu_first -o MNI/MNI_FIRST-L_Accu_corr -i MNI152_T1_1mm_brain -b fast
/usr/local/fsl/bin/run_first -i MNI152_T1_1mm_brain -t MNI152_T1_1mm_brain_to_std_sub.mat -n 50 -o MNI/MNI_FIRST-L_Amyg_first -m /usr/local/fsl/data/first/models_336_bin/intref_thal/L_Amyg.bmv -intref /usr/local/fsl/data/first/models_336_bin/05mm/L_Thal_05mm.bmv; /usr/local/fsl/bin/first_boundary_corr -s MNI/MNI_FIRST-L_Amyg_first -o MNI/MNI_FIRST-L_Amyg_corr -i MNI152_T1_1mm_brain -b fast
/usr/local/fsl/bin/run_first -i MNI152_T1_1mm_brain -t MNI152_T1_1mm_brain_to_std_sub.mat -n 30 -o MNI/MNI_FIRST-L_Caud_first -m /usr/local/fsl/data/first/models_336_bin/intref_thal/L_Caud.bmv -intref /usr/local/fsl/data/first/models_336_bin/05mm/L_Thal_05mm.bmv; /usr/local/fsl/bin/first_boundary_corr -s MNI/MNI_FIRST-L_Caud_first -o MNI/MNI_FIRST-L_Caud_corr -i MNI152_T1_1mm_brain -b fast
/usr/local/fsl/bin/run_first -i MNI152_T1_1mm_brain -t MNI152_T1_1mm_brain_to_std_sub.mat -n 30 -o MNI/MNI_FIRST-L_Hipp_first -m /usr/local/fsl/data/first/models_336_bin/intref_thal/L_Hipp.bmv -intref /usr/local/fsl/data/first/models_336_bin/05mm/L_Thal_05mm.bmv; /usr/local/fsl/bin/first_boundary_corr -s MNI/MNI_FIRST-L_Hipp_first -o MNI/MNI_FIRST-L_Hipp_corr -i MNI152_T1_1mm_brain -b fast
/usr/local/fsl/bin/run_first -i MNI152_T1_1mm_brain -t MNI152_T1_1mm_brain_to_std_sub.mat -n 40 -o MNI/MNI_FIRST-L_Pall_first -m /usr/local/fsl/data/first/models_336_bin/05mm/L_Pall_05mm.bmv; /usr/local/fsl/bin/first_boundary_corr -s MNI/MNI_FIRST-L_Pall_first -o MNI/MNI_FIRST-L_Pall_corr -i MNI152_T1_1mm_brain -b none
/usr/local/fsl/bin/run_first -i MNI152_T1_1mm_brain -t MNI152_T1_1mm_brain_to_std_sub.mat -n 40 -o MNI/MNI_FIRST-L_Puta_first -m /usr/local/fsl/data/first/models_336_bin/05mm/L_Puta_05mm.bmv; /usr/local/fsl/bin/first_boundary_corr -s MNI/MNI_FIRST-L_Puta_first -o MNI/MNI_FIRST-L_Puta_corr -i MNI152_T1_1mm_brain -b none
/usr/local/fsl/bin/run_first -i MNI152_T1_1mm_brain -t MNI152_T1_1mm_brain_to_std_sub.mat -n 40 -o MNI/MNI_FIRST-L_Thal_first -m /usr/local/fsl/data/first/models_336_bin/05mm/L_Thal_05mm.bmv; /usr/local/fsl/bin/first_boundary_corr -s MNI/MNI_FIRST-L_Thal_first -o MNI/MNI_FIRST-L_Thal_corr -i MNI152_T1_1mm_brain -b none
/usr/local/fsl/bin/run_first -i MNI152_T1_1mm_brain -t MNI152_T1_1mm_brain_to_std_sub.mat -n 50 -o MNI/MNI_FIRST-R_Accu_first -m /usr/local/fsl/data/first/models_336_bin/R_Accu_bin.bmv; /usr/local/fsl/bin/first_boundary_corr -s MNI/MNI_FIRST-R_Accu_first -o MNI/MNI_FIRST-R_Accu_corr -i MNI152_T1_1mm_brain -b fast
/usr/local/fsl/bin/run_first -i MNI152_T1_1mm_brain -t MNI152_T1_1mm_brain_to_std_sub.mat -n 50 -o MNI/MNI_FIRST-R_Amyg_first -m /usr/local/fsl/data/first/models_336_bin/intref_thal/R_Amyg.bmv -intref /usr/local/fsl/data/first/models_336_bin/05mm/R_Thal_05mm.bmv; /usr/local/fsl/bin/first_boundary_corr -s MNI/MNI_FIRST-R_Amyg_first -o MNI/MNI_FIRST-R_Amyg_corr -i MNI152_T1_1mm_brain -b fast
/usr/local/fsl/bin/run_first -i MNI152_T1_1mm_brain -t MNI152_T1_1mm_brain_to_std_sub.mat -n 30 -o MNI/MNI_FIRST-R_Caud_first -m /usr/local/fsl/data/first/models_336_bin/intref_thal/R_Caud.bmv -intref /usr/local/fsl/data/first/models_336_bin/05mm/R_Thal_05mm.bmv; /usr/local/fsl/bin/first_boundary_corr -s MNI/MNI_FIRST-R_Caud_first -o MNI/MNI_FIRST-R_Caud_corr -i MNI152_T1_1mm_brain -b fast
/usr/local/fsl/bin/run_first -i MNI152_T1_1mm_brain -t MNI152_T1_1mm_brain_to_std_sub.mat -n 30 -o MNI/MNI_FIRST-R_Hipp_first -m /usr/local/fsl/data/first/models_336_bin/intref_thal/R_Hipp.bmv -intref /usr/local/fsl/data/first/models_336_bin/05mm/R_Thal_05mm.bmv; /usr/local/fsl/bin/first_boundary_corr -s MNI/MNI_FIRST-R_Hipp_first -o MNI/MNI_FIRST-R_Hipp_corr -i MNI152_T1_1mm_brain -b fast
/usr/local/fsl/bin/run_first -i MNI152_T1_1mm_brain -t MNI152_T1_1mm_brain_to_std_sub.mat -n 40 -o MNI/MNI_FIRST-R_Pall_first -m /usr/local/fsl/data/first/models_336_bin/05mm/R_Pall_05mm.bmv; /usr/local/fsl/bin/first_boundary_corr -s MNI/MNI_FIRST-R_Pall_first -o MNI/MNI_FIRST-R_Pall_corr -i MNI152_T1_1mm_brain -b none
/usr/local/fsl/bin/run_first -i MNI152_T1_1mm_brain -t MNI152_T1_1mm_brain_to_std_sub.mat -n 40 -o MNI/MNI_FIRST-R_Puta_first -m /usr/local/fsl/data/first/models_336_bin/05mm/R_Puta_05mm.bmv; /usr/local/fsl/bin/first_boundary_corr -s MNI/MNI_FIRST-R_Puta_first -o MNI/MNI_FIRST-R_Puta_corr -i MNI152_T1_1mm_brain -b none
/usr/local/fsl/bin/run_first -i MNI152_T1_1mm_brain -t MNI152_T1_1mm_brain_to_std_sub.mat -n 40 -o MNI/MNI_FIRST-R_Thal_first -m /usr/local/fsl/data/first/models_336_bin/05mm/R_Thal_05mm.bmv; /usr/local/fsl/bin/first_boundary_corr -s MNI/MNI_FIRST-R_Thal_first -o MNI/MNI_FIRST-R_Thal_corr -i MNI152_T1_1mm_brain -b none
/usr/local/fsl/bin/run_first -i MNI152_T1_1mm_brain -t MNI152_T1_1mm_brain_to_std_sub.mat -n 40 -o MNI/MNI_FIRST-BrStem_first -m /usr/local/fsl/data/first/models_336_bin/BrStem_bin.bmv; /usr/local/fsl/bin/first_boundary_corr -s MNI/MNI_FIRST-BrStem_first -o MNI/MNI_FIRST-BrStem_corr -i MNI152_T1_1mm_brain -b fast
